language: node_js

node_js:
  - "11.15.0"

branches:
  only:
    - source

env:
 global:
   - GH_REF: github.com/mzvast/mzvast.github.io.git

cache: yarn

install:
  - yarn --ignore-engines

script:
  - CI=false && npm run build
  - npm run build-index

after_script:
  - cd ./build
  - git init
  - git config user.name "mzvast"
  - git config user.email "mzvast@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master