name: Docs Release

on:
  push:
    branches: [source]
    paths:
      - src/**
  pull_request:
    branches: [source]
    paths:
      - src/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 11.15.0
        uses: actions/setup-node@v2
        with:
          node-version: "11.15.0"
          cache: "yarn"

      - name: Install
        run: yarn --frozen-lockfile --ignore-engines

      - name: Build
        run: |
          CI=false && npm run build
          npm run build-index

      - name: Release to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy -- -u "github-actions-bot <support+actions@github.com>"
